### ISSUE TITLE
Support for armv7-unknown-linux-musleabihf

### ISSUE THREAD

**Issue by jimmycuadra** [clux/muslrust#11]
Any interest in supporting more architectures than x86_64-unknown-linux-musl? I'm working on a project where I want to run a Rust program via Docker on a Raspberry Pi 3, and was looking into ways of doing that. I've been using this project for several images for a while now—it's fantastic. I figured before I fork it and badly maintain an ARM equivalent, I'd ask whether it was worth trying to support in this project proper. Thanks for your time and the wonderful project!

**Comment by clux** [comment]
Hey there, thanks again for the support.

Honestly though, I'm not convinced this project is actually necessary anymore.
What's your opinion of [cross](https://github.com/japaric/cross)? It provides images like this one, but does it with a general tool that allows tons of [architectures](https://github.com/japaric/cross/tree/master/docker).

I can see the `armv7-unknown-linux-musleabihf` target supported there, though apparently without openssl, but maybe it's a better place to start.

I'm kind of considering just redirecting people there and telling them to use `cross build --target x86_64-unknown-linux-musl --release` instead. It is a more general solution.

**Comment by jimmycuadra** [comment]
Oh, yes, that seems quite appropriate. I remember seeing the announcement of cross a few months back, but didn't take a close look at it. I wonder why OpenSSL is listed as not applicable musl targets. I'll open an issue over there and reference this one. Thanks!

**Comment by corbinu** [comment]
Just a note this works for building from a Mac/Windows as long as docker is installed where as cross does not so I do think this project still has legs. :)

**Comment by clux** [comment]
Oh nice, yeah that makes sense. I noticed later on that `cross` mounts a bunch of cargo and rustup folders and relies on getting the toolchains updates outside the image. I haven't fully grokked how that actually works, but it's nice that you don't need to upgrade the images all the time. On the other hand, it's not great because you need to have rust set up outside of it to use it as you say.

I will keep posting updates to the images at least. Maybe it could actually be worth adding support for other images as well. Travis builds and dockerhub usage is free from my perspective at least 😏
