### ISSUE TITLE
GitHub actions example does not seem to use this project anymore

### ISSUE THREAD

**Issue by hoijui** [clux/muslrust#145]
In the README, there is this link:

[Github release assets uploaded via github actions](https://github.com/kube-rs/kopium/blob/main/.github/workflows/release.yml)

but I can not find anything about `muslrust` there.
It looks like it was removed in this commit:
https://github.com/kube-rs/kopium/commit/f3f3fac47eda2b33e0a3ae553ae03ba355316a28
is there na other example, or should it instead link to the old version (before that commit)?

**Comment by clux** [comment]
Thanks for this. I had forgotten I linked to this. I might link to the old sha for now, as I've stopped using muslrust for CLI style release binaries due to generally needing more than 2 platforms for them. 

It's probably more practical to use muslrust these days for cloud images that's usually either amd64 or arm64. That said, if anyone has a more up-to-date usage of muslrust for CLI releases, feel free to submit a PR with an up-to-date link.
