### ISSUE TITLE
Cargo Tarpaulin

### ISSUE THREAD

**Issue by dweidenfeld** [clux/muslrust#51]
Hi,

just wanted to ask if someone made `cargo-tarpaulin` working in this container (or musl in general).
https://github.com/xd009642/tarpaulin

Thanks & regards
Dominik

**Comment by clux** [comment]
I seem to recall it being harder to build before, but judging by their README now there's only a few dependencies that we should have already:

```sh
apt-get update && apt-get install libssl-dev pkg-config cmake zlib1g-dev
```

it might not be too bad to get this working or added. Worth investigating!

**Comment by dweidenfeld** [comment]
Thanks!
Just ask me if you need/want support ;)

**Comment by clux** [comment]
Thinking about this again, I think it probably make sense to limit the size of this image small enough to be maintainable. People can add builders on top if they absolutely need this.

Also, even when building for musl in the general case, I generally take advantage of code coverage / clippy in the standard ci architecture (because they tend to be separate jobs and need separate CI caching anyway).
