### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by rrichardson** [clux/muslrust#6]
This isn't an issue. I just wanted to say this worked very well and it saved me a ton of time with regards to messing with static openssl.  

On Fedora,  the user running in the container will not have access to the homedir or anything in it. 

I did have to do some mucking around with users and permissions to be able to use my build dir within the container.  I can post my bash script I used to wrap that if needed.

**Comment by clux** [comment]
Glad it's useful :)

Sure, post away, I only have a few examples of using this in the wild. Did you need the home dir for anything in particular?

**Comment by rrichardson** [comment]
All of my dev projects are in my home dir, so building my binaries and docker images from there is the most convenient.  If there is a better approach than this, let me know.  

(Adapted from a stack-overflow answer which I can't seem to find anymore) 

```bash
#!/bin/bash

DOCKER_IMAGE='clux/muslrust'
CONTAINER_USERNAME='dummy'
CONTAINER_GROUPNAME='dummy'
HOMEDIR='/home/'$CONTAINER_USERNAME
GROUP_ID=$(id -g)
USER_ID=$(id -u)

### FUNCTIONS

create_user_cmd()
{
  echo \
    groupadd -f -g $GROUP_ID $CONTAINER_GROUPNAME '&&' \
    useradd -u $USER_ID -g $CONTAINER_GROUPNAME $CONTAINER_USERNAME '&&' \
    chown -R $CONTAINER_USERNAME:$CONTAINER_GROUPNAME $HOMEDIR '&&' \
    cd $HOMEDIR 
}
    
#mkdir --parent $HOMEDIR '&&' \

execute_as_cmd()
{
  echo \
    su $CONTAINER_USERNAME -c 
}

full_container_cmd()
{
  echo "'$(create_user_cmd) && $(execute_as_cmd) \"$@\"'"
}

### MAIN

eval sudo docker run -it \
    --rm=true \
    -a stdout \
    --privileged=true \
    -v $(pwd):$HOMEDIR \
    $DOCKER_IMAGE \
    /bin/bash -ci $(full_container_cmd "$@")
```

run with 
``` 
run_in_docker.sh cargo build --release
```
this will run as you, so you don't need to muck about with the perms of the created binary
```

**Comment by clux** [comment]
Huh, that's interesting. I've never seen docker set up in such a way that you need to use `docker run` with `sudo`. And you also seem to need `--privileged`. That is weird.

You are nicely solving the problem of the remapped ids. The normal solution to this is to just have the container add a user (first always gets id 1000) and rely on the assumption that >95% of linux users are using the first users with ids 1000:1000 anyway. Yours is more general though.

I've also seen some people use [gosu](https://github.com/tianon/gosu) with some effort, but the future solution is meant to be docker namespaces (userns-remap). Unfortunately, those are kind of a pain to work with, having many limitations on the run command itself. 

Nothing like this is in the base image at the moment because you can do without it in [CI environments without much faff](https://github.com/clux/blog/blob/f735a05eafbaa644a4b68ee2271ef15a8772f019/.travis.yml#L18-L19). Generally just grab the executable and stuff it in a docker image or chown it. It does screw up permissions of your target/ dirs if you use it locally though, which is a bit of a pain. But I don't normally build musl binaries outside CI - that's normally the release stage for me/company.

With some wrappers like the one you have, or some kind of aggressive chown script, it's not too bad to build them locally though. 😄

**Comment by rrichardson** [comment]
Fedora is a bit more paranoid than most distros with regards to Docker, since it is a simple vector to arbitrary execution as root :)

And yea, for CI, I figure it will be running inside of another docker image with "root" access.  Once I get done mucking with my app that's probably where it will end up.

**Comment by clux** [comment]
Hehe, fair enough. Thanks for sharing this.

**Comment by bencord0** [comment]
One idiom that I have seen being used, to avoid the permissions mismatch between the host and the container is to use a mix of Dockerfile ADD and the docker cp command.

Dockerfile
```
FROM clux/muslrust
WORKDIR /app
ADD . /app
```
```
imgid=$(docker build -q .)
cid=$(docker run -d -w /app $imgid cargo build --release)
docker wait $cid
docker cp $cid /app/target ./target
```

---
I think the `sudo docker` convention is a RedHatism to set the docker unix socket only accessible by root. Probably because of...
```
docker run -v /:/chroot -it busybox chroot /chroot
```

**Comment by clux** [comment]
Ohh, that's quite nice actually. Allows you to not have to recompile everything after doing a musl build when going back to default debug/release because the modified target directory is not shared / partially mangled.
