### ISSUE TITLE
Out of date Git version

### ISSUE THREAD

**Issue by JohnDoneth** [clux/muslrust#88]
Because this container uses the version of Git 2.7.4, because it's using Ubuntu 16.04, downloading submodules with GitHub Actions checkout doesn't seem to work as it requires Git 2.18 or above.

**Error**
```
Error: Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH.
```

**Relevent PR**
https://github.com/gleam-lang/gleam/pull/1413

**Actions Run**
https://github.com/gleam-lang/gleam/runs/4629333291

**Comment by clux** [comment]
Ah, damn. That's annoying. Haven't tried to upgrade to xenial or newer (#21) in quite some time because it came with some more issues. Might have to try it again.

Don't have time to look at this for a while though, so will have to leave it as help wanted for now.

A temporary work around would be to not run the checkout action under this image, and use `docker run` to build your image [manually in a later step](https://github.com/kube-rs/controller-rs/blob/deec3101cfd866316254aed2a44a7c3ee7102721/.github/workflows/ci.yml#L76-L85).

**Comment by JohnDoneth** [comment]
Using `docker run` worked great. Thanks for the suggestion!
